# Generated by Django 4.2.7 on 2023-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_no', models.CharField(max_length=20)),
            ],
        ),
    ]
