# Generated by Django 4.2.7 on 2023-11-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facedetection.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facedetection.students')),
            ],
        ),
    ]
