# Generated by Django 4.2.7 on 2023-11-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='face_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
