# Generated by Django 4.1.7 on 2023-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0004_students_face_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
